import { EmployeeType } from './interface';

const EmployeeData: EmployeeType[] = [
  {
    id: 'a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    image: 'https://chanzuckerberg.com/wp-content/uploads/2022/03/p_edit-2022-v2.jpg',
    age: 28,
    gender: 'Woman',
    role: 'Frontend Engineer',
    department: 'Finance Department',
    title: 'Entry-Level',
    contacts: [
      { type: 'phone', value: '1234567890' },
      { type: 'email', value: 'alice@example.com' },
      { type: 'instagram', value: '@alice' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/alice' },
    ],
    address: {
      address: '789 Oak St',
      zipcode: 67890,
      city: 'Villagetown',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Achievement in Web Development',
        description: 'Awarded for outstanding performance in web development.',
        dateUpload: '2023-01-01',
      },
    ],
  },
  {
    id: 'b2c3d4e5-f6g7-h8i9-j0k1-l2m3n4o5p6q7',
    name: 'Bob Smith',
    email: 'bob@example.com',
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg',
    age: 35,
    gender: 'Man',
    role: 'Backend Engineer',
    department: 'Research & Technology',
    title: 'Mid-Level',
    contacts: [
      { type: 'phone', value: '0987654321' },
      { type: 'email', value: 'bob@example.com' },
      { type: 'instagram', value: '@bob' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/bob' },
    ],
    address: {
      address: '987 Pine St',
      zipcode: 54321,
      city: 'Cityville',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Excellence in Database Management',
        description: 'Awarded for exceptional skills in database management.',
        dateUpload: '2023-02-15',
      },
    ],
  },
  {
    id: 'c3d4e5f6-g7h8-i9j0-k1l2-m3n4o5p6q7r8',
    name: 'Carol Williams',
    email: 'carol@example.com',
    image: 'https://chanzuckerberg.com/wp-content/uploads/2022/03/p_edit-2022-v2.jpg',
    age: 40,
    gender: 'Woman',
    role: 'AI Engineer',
    department: 'Finance Department',
    title: 'Senior-Level',
    contacts: [
      { type: 'phone', value: '9876543210' },
      { type: 'email', value: 'carol@example.com' },
      { type: 'instagram', value: '@carol' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/carol' },
    ],
    address: {
      address: '654 Maple St',
      zipcode: 43210,
      city: 'Townsville',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Mastery in Machine Learning',
        description: 'Awarded for mastery in machine learning techniques.',
        dateUpload: '2023-03-20',
      },
    ],
  },
  {
    id: 'd4e5f6g7-h8i9-j0k1-l2m3-n4o5p6q7r8s9',
    name: 'David Brown',
    email: 'david@example.com',
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg',
    age: 45,
    gender: 'Man',
    role: 'QA Engineer',
    department: 'Finance Department',
    title: 'Mid-Level',
    contacts: [
      { type: 'phone', value: '1234567890' },
      { type: 'email', value: 'david@example.com' },
      { type: 'instagram', value: '@david' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/david' },
    ],
    address: {
      address: '321 Cedar St',
      zipcode: 12345,
      city: 'Hamletville',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Excellence in Software Testing',
        description: 'Awarded for excellence in software testing techniques.',
        dateUpload: '2023-04-25',
      },
    ],
  },
  {
    id: 'e5f6g7h8-i9j0-k1l2-m3n4-o5p6q7r8s9t0',
    name: 'Emily Jones',
    email: 'emily@example.com',
    image: 'https://chanzuckerberg.com/wp-content/uploads/2022/03/p_edit-2022-v2.jpg',
    age: 32,
    gender: 'Woman',
    role: 'HR',
    department: 'Finance Department',
    title: 'Entry-Level',
    contacts: [
      { type: 'phone', value: '0987654321' },
      { type: 'email', value: 'emily@example.com' },
      { type: 'instagram', value: '@emily' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/emily' },
    ],
    address: {
      address: '456 Birch St',
      zipcode: 56789,
      city: 'Forestville',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Achievement in Employee Relations',
        description: 'Awarded for excellence in employee relations.',
        dateUpload: '2023-05-30',
      },
    ],
  },
  {
    id: 'f6g7h8i9-j0k1-l2m3-n4o5-p6q7r8s9t0u1',
    name: 'Frank Davis',
    email: 'frank@example.com',
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg',
    age: 50,
    gender: 'Man',
    role: 'Frontend Engineer',
    department: 'Research & Technology',
    title: 'Senior-Level',
    contacts: [
      { type: 'phone', value: '1234567890' },
      { type: 'email', value: 'frank@example.com' },
      { type: 'instagram', value: '@frank' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/frank' },
    ],
    address: {
      address: '789 Elm St',
      zipcode: 98765,
      city: 'Metropolis',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Excellence in Web Development',
        description: 'Awarded for outstanding performance in web development.',
        dateUpload: '2023-06-15',
      },
    ],
  },
  {
    id: 'g7h8i9j0-k1l2-m3n4-o5p6-q7r8s9t0u1v2',
    name: 'Grace Wilson',
    email: 'grace@example.com',
    image: 'https://chanzuckerberg.com/wp-content/uploads/2022/03/p_edit-2022-v2.jpg',
    age: 38,
    gender: 'Woman',
    role: 'Backend Engineer',
    department: 'Research & Technology',
    title: 'Mid-Level',
    contacts: [
      { type: 'phone', value: '0987654321' },
      { type: 'email', value: 'grace@example.com' },
      { type: 'instagram', value: '@grace' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/grace' },
    ],
    address: {
      address: '123 Cedar St',
      zipcode: 13579,
      city: 'Villageville',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Excellence in Database Management',
        description: 'Awarded for exceptional skills in database management.',
        dateUpload: '2023-07-20',
      },
    ],
  },
  {
    id: 'h8i9j0k1-l2m3-n4o5-p6q7-r8s9t0u1v2w3',
    name: 'Harry Miller',
    email: 'harry@example.com',
    image: 'https://asset.kompas.com/crops/GQUver5Id7jVYzbXgJveT7OJ0qg=/65x0:650x390/1200x800/data/photo/2015/10/27/1658302Mark-Jadi780x390.jpg',
    age: 55,
    gender: 'Man',
    role: 'AI Engineer',
    department: 'Research & Technology',
    title: 'Senior-Level',
    contacts: [
      { type: 'phone', value: '1234567890' },
      { type: 'email', value: 'harry@example.com' },
      { type: 'instagram', value: '@harry' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/harry' },
    ],
    address: {
      address: '456 Oak St',
      zipcode: 24680,
      city: 'Citytown',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Mastery in Machine Learning',
        description: 'Awarded for mastery in machine learning techniques.',
        dateUpload: '2023-08-25',
      },
    ],
  },
  {
    id: 'i9j0k1l2-m3n4-o5p6q7-r8s9t0u1-v2w3x4y5',
    name: 'Ivy White',
    email: 'ivy@example.com',
    image: 'https://images.squarespace-cdn.com/content/v1/5bdc9a953917ee92aca73364/1612505480509-G4626T6BTTKRWLKZ0VDM/Priscilla%2BHi%2BRes%2B%25281%2529.jpg',
    age: 42,
    gender: 'Woman',
    role: 'QA Engineer',
    department: 'Research & Technology',
    title: 'Senior-Level',
    contacts: [
      { type: 'phone', value: '0987654321' },
      { type: 'email', value: 'ivy@example.com' },
      { type: 'instagram', value: '@ivy' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/ivy' },
    ],
    address: {
      address: '789 Maple St',
      zipcode: 35791,
      city: 'Treetown',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Excellence in Software Testing',
        description: 'Awarded for excellence in software testing techniques.',
        dateUpload: '2023-09-30',
      },
    ],
  },
  {
    id: 'j0k1l2m3-n4o5-p6q7-r8s9t0u1-v2w3x4y5z6',
    name: 'Jack Brown',
    email: 'jack@example.com',
    image: 'https://asset.kompas.com/crops/GQUver5Id7jVYzbXgJveT7OJ0qg=/65x0:650x390/1200x800/data/photo/2015/10/27/1658302Mark-Jadi780x390.jpg',
    age: 48,
    gender: 'Man',
    role: 'HR',
    department: 'Finance Department',
    title: 'Mid-Level',
    contacts: [
      { type: 'phone', value: '1234567890' },
      { type: 'email', value: 'jack@example.com' },
      { type: 'instagram', value: '@jack' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/jack' },
    ],
    address: {
      address: '987 Birch St',
      zipcode: 57913,
      city: 'Woodville',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Achievement in Employee Relations',
        description: 'Awarded for excellence in employee relations.',
        dateUpload: '2023-10-15',
      },
    ],
  },
  {
    id: 'k1l2m3n4-o5p6-q7r8s9t0u1-v2w3x4y5z6a7',
    name: 'Kelly Wilson',
    email: 'kelly@example.com',
    image: 'https://images.squarespace-cdn.com/content/v1/5bdc9a953917ee92aca73364/1612505480509-G4626T6BTTKRWLKZ0VDM/Priscilla%2BHi%2BRes%2B%25281%2529.jpg',
    age: 38,
    gender: 'Woman',
    role: 'Frontend Engineer',
    department: 'Finance Department',
    title: 'Mid-Level',
    contacts: [
      { type: 'phone', value: '0987654321' },
      { type: 'email', value: 'kelly@example.com' },
      { type: 'instagram', value: '@kelly' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/kelly' },
    ],
    address: {
      address: '123 Cedar St',
      zipcode: 13579,
      city: 'Villageville',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Excellence in Web Development',
        description: 'Awarded for outstanding performance in web development.',
        dateUpload: '2023-11-20',
      },
    ],
  },
  {
    id: 'l2m3n4o5-p6q7-r8s9t0u1-v2w3x4y5z6a7b8',
    name: 'Larry Miller',
    email: 'larry@example.com',
    image: 'https://asset.kompas.com/crops/GQUver5Id7jVYzbXgJveT7OJ0qg=/65x0:650x390/1200x800/data/photo/2015/10/27/1658302Mark-Jadi780x390.jpg',
    age: 55,
    gender: 'Man',
    role: 'Backend Engineer',
    department: 'Research & Technology',
    title: 'Senior-Level',
    contacts: [
      { type: 'phone', value: '1234567890' },
      { type: 'email', value: 'larry@example.com' },
      { type: 'instagram', value: '@larry' },
      { type: 'linkedin', value: 'https://www.linkedin.com/in/larry' },
    ],
    address: {
      address: '456 Oak St',
      zipcode: 24680,
      city: 'Citytown',
      country: 'USA',
    },
    certificates: [
      {
        name: 'Certificate of Excellence in Database Management',
        description: 'Awarded for exceptional skills in database management.',
        dateUpload: '2023-12-25',
      },
    ],
  },
];

export default EmployeeData;
